#define NOMINMAX
#include <windows.h>
#include <windowsx.h>
#include <commctrl.h>
#include <commdlg.h>
#include <richedit.h>
#include <shlobj.h>
#include <shellapi.h>
#include <shlwapi.h>
#include <filesystem>
#include <fstream>
#include <map>
#include <mutex>
#include <regex>
#include <sstream>
#include <thread>
#include <atomic>
#include "core.hpp"

using namespace pylite; namespace fs=std::filesystem;
constexpr int ID_TREE=100,ID_EDIT=101,ID_OUTPUT=102,ID_SAVE=103,ID_PY=104,ID_RUN=105,ID_CLEAR=106,ID_TOGGLE=107,ID_STATUS=108,ID_POPUP=109;
enum {CMD_NEW=200,CMD_OPEN,CMD_FOLDER,CMD_SAVE,CMD_SAVEAS,CMD_EXIT,CMD_UNDO,CMD_REDO,CMD_CUT,CMD_COPY,CMD_PASTE,CMD_ALL,CMD_RUN,CMD_STOP,CMD_TOGGLE,CMD_SELECTPY,CMD_REGISTER,CMD_UNREGISTER,CMD_ABOUT};
constexpr UINT WM_APPEND=WM_APP+1,WM_RUNEND=WM_APP+2,WM_INTERPRETER=WM_APP+3,WM_COMPLETIONS=WM_APP+4;
HINSTANCE gInst{}; HWND gMain{},gTree{},gEdit{},gOutput{},gStatus{},gPy{},gRun{},gSave{},gFolder{},gClear{},gToggle{},gPopup{}; HFONT gUiFont{},gCodeFont{};
std::wstring gFile,gRoot,gInterpreter,gEncoding=L"UTF-8"; bool gDirty=false,gOutputCollapsed=false,gRunning=false,gFormatting=false; int gLeft=190,gRight=205,gOutputHeight=180,gSavedOutput=180; int gDrag=0; POINT gDragStart{}; int gDragValue{};
HANDLE gProcess=nullptr,gJob=nullptr; std::atomic<unsigned> gCompletionRequest{0}; std::map<std::wstring,std::vector<std::wstring>> gModuleCache; std::mutex gCacheMutex;

std::wstring W(const std::string&s){if(s.empty())return{};int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0);std::wstring o(n,0);MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),o.data(),n);return o;}
std::string U8(const std::wstring&s){if(s.empty())return{};int n=WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0,nullptr,nullptr);std::string o(n,0);WideCharToMultiByte(CP_UTF8,0,s.data(),(int)s.size(),o.data(),n,nullptr,nullptr);return o;}
std::wstring BaseName(const std::wstring&p){auto n=fs::path(p).filename().wstring();return n.empty()?L"未命名.py":n;}
std::wstring SettingsPath(){wchar_t p[MAX_PATH]{};SHGetFolderPathW(nullptr,CSIDL_APPDATA,nullptr,SHGFP_TYPE_CURRENT,p);fs::path d=fs::path(p)/L"PyLite";std::error_code ec;fs::create_directories(d,ec);return(d/L"settings.json").wstring();}
void SetStatus(const std::wstring&s){SendMessageW(gStatus,SB_SETTEXT,0,(LPARAM)s.c_str());}
void UpdateTitle(){std::wstring t=BaseName(gFile)+(gDirty?L" * — PyLite":L" — PyLite");SetWindowTextW(gMain,t.c_str());}
std::wstring EditorText(){int n=GetWindowTextLengthW(gEdit);std::wstring s(n,0);GetWindowTextW(gEdit,s.data(),n+1);return s;}
void SetEditorText(const std::wstring&s){gFormatting=true;SetWindowTextW(gEdit,s.c_str());SendMessageW(gEdit,EM_SETMODIFY,FALSE,0);gDirty=false;gFormatting=false;UpdateTitle();}
void SaveSettings(){auto settings=SettingsPath();std::ofstream f(settings.c_str(),std::ios::binary);f<<"{\n  \"python\": \"";for(char c:U8(gInterpreter)){if(c=='\\'||c=='\"')f<<'\\';f<<c;}f<<"\",\n  \"left\": "<<gLeft<<",\n  \"right\": "<<gRight<<",\n  \"output\": "<<gSavedOutput<<",\n  \"collapsed\": "<<(gOutputCollapsed?"true":"false")<<",\n  \"folder\": \"";for(char c:U8(gRoot)){if(c=='\\'||c=='\"')f<<'\\';f<<c;}f<<"\"\n}\n";}
std::string JsonString(const std::string&s,const char*key){std::smatch m;std::regex r(std::string("\\\"")+key+"\\\"\\s*:\\s*\\\"((?:\\\\.|[^\\\"])*)\\\"");if(!std::regex_search(s,m,r))return{};std::string o;bool esc=false;for(char c:m[1].str()){if(esc){o+=c;esc=false;}else if(c=='\\')esc=true;else o+=c;}return o;}
int JsonInt(const std::string&s,const char*k,int d){std::smatch m;return std::regex_search(s,m,std::regex(std::string("\\\"")+k+"\\\"\\s*:\\s*(\\d+)"))?std::stoi(m[1].str()):d;}
void LoadSettings(){auto settings=SettingsPath();std::ifstream f(settings.c_str(),std::ios::binary);if(!f)return;std::string s((std::istreambuf_iterator<char>(f)),{});try{gInterpreter=W(JsonString(s,"python"));gRoot=W(JsonString(s,"folder"));gLeft=std::clamp(JsonInt(s,"left",190),145,400);gRight=std::clamp(JsonInt(s,"right",205),150,400);gSavedOutput=std::clamp(JsonInt(s,"output",180),80,400);gOutputCollapsed=s.find("\"collapsed\": true")!=std::string::npos;}catch(...){gLeft=190;gRight=205;gSavedOutput=180;gOutputCollapsed=false;}}

bool DecodeFile(const std::wstring&path,std::wstring&out){std::ifstream f(fs::path(path),std::ios::binary);if(!f){MessageBoxW(gMain,L"无法读取文件。",L"PyLite",MB_ICONERROR);return false;}std::string b((std::istreambuf_iterator<char>(f)),{});UINT cp=CP_UTF8;int off=0;if(b.size()>=3&&(unsigned char)b[0]==0xEF&&(unsigned char)b[1]==0xBB&&(unsigned char)b[2]==0xBF){off=3;gEncoding=L"UTF-8 BOM";}else{auto e=DetectPep263(b);if(e=="gbk"||e=="gb2312"||e=="cp936"){cp=936;gEncoding=L"GBK";}else if(e=="latin-1"||e=="iso-8859-1"){cp=28591;gEncoding=L"Latin-1";}else gEncoding=L"UTF-8";}int flags=cp==CP_UTF8?MB_ERR_INVALID_CHARS:0;int n=MultiByteToWideChar(cp,flags,b.data()+off,(int)b.size()-off,nullptr,0);if(n<=0&&b.size()>off){MessageBoxW(gMain,L"文件编码无法识别，未打开以避免损坏。",L"编码错误",MB_ICONERROR);return false;}out.resize(n);MultiByteToWideChar(cp,flags,b.data()+off,(int)b.size()-off,out.data(),n);return true;}
bool SaveTo(const std::wstring&path){auto s=EditorText();UINT cp=gEncoding==L"GBK"?936:gEncoding==L"Latin-1"?28591:CP_UTF8;int n=WideCharToMultiByte(cp,WC_NO_BEST_FIT_CHARS,s.data(),(int)s.size(),nullptr,0,nullptr,nullptr);std::string b(n,0);BOOL used=FALSE;WideCharToMultiByte(cp,WC_NO_BEST_FIT_CHARS,s.data(),(int)s.size(),b.data(),n,nullptr,&used);if(used&&cp!=CP_UTF8){MessageBoxW(gMain,L"当前编码无法表示部分字符，请另存为 UTF-8。",L"编码错误",MB_ICONERROR);return false;}std::ofstream f(fs::path(path),std::ios::binary|std::ios::trunc);if(!f){MessageBoxW(gMain,L"无法保存文件。",L"PyLite",MB_ICONERROR);return false;}if(gEncoding==L"UTF-8 BOM")f.write("\xEF\xBB\xBF",3);f.write(b.data(),b.size());gFile=path;gDirty=false;SendMessage(gEdit,EM_SETMODIFY,FALSE,0);UpdateTitle();SetStatus(L"已保存");return true;}
std::wstring FileDialog(bool save){wchar_t p[32768]{};if(!gFile.empty())wcscpy_s(p,gFile.c_str());OPENFILENAMEW o{sizeof(o)};o.hwndOwner=gMain;o.lpstrFile=p;o.nMaxFile=32768;o.lpstrFilter=L"Python 文件 (*.py;*.pyw)\0*.py;*.pyw\0所有文件\0*.*\0";o.lpstrDefExt=L"py";o.Flags=OFN_EXPLORER|OFN_PATHMUSTEXIST|(save?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST);return(save?GetSaveFileNameW(&o):GetOpenFileNameW(&o))?p:L"";}
std::wstring FolderDialog(){IFileDialog*d=nullptr;std::wstring r;if(SUCCEEDED(CoCreateInstance(CLSID_FileOpenDialog,nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&d)))){DWORD o;d->GetOptions(&o);d->SetOptions(o|FOS_PICKFOLDERS|FOS_FORCEFILESYSTEM);if(SUCCEEDED(d->Show(gMain))){IShellItem*i=nullptr;if(SUCCEEDED(d->GetResult(&i))){PWSTR p=nullptr;if(SUCCEEDED(i->GetDisplayName(SIGDN_FILESYSPATH,&p))){r=p;CoTaskMemFree(p);}i->Release();}}d->Release();}return r;}
bool ConfirmDiscard(){if(!gDirty)return true;int r=MessageBoxW(gMain,L"当前文件有未保存修改，是否保存？",L"PyLite",MB_YESNOCANCEL|MB_ICONWARNING);if(r==IDCANCEL)return false;if(r==IDNO)return true;SendMessage(gMain,WM_COMMAND,CMD_SAVE,0);return !gDirty;}

void AddDummy(HTREEITEM h){TVINSERTSTRUCTW t{};t.hParent=h;t.hInsertAfter=TVI_LAST;t.item.mask=TVIF_TEXT|TVIF_PARAM;t.item.pszText=(LPWSTR)L"";t.item.lParam=0;TreeView_InsertItem(gTree,&t);}
HTREEITEM AddTree(HTREEITEM parent,const fs::path&p,bool dir){auto*stored=new std::wstring(p.wstring());TVINSERTSTRUCTW t{};t.hParent=parent;t.hInsertAfter=TVI_LAST;t.item.mask=TVIF_TEXT|TVIF_PARAM|TVIF_CHILDREN;auto label=p.filename().wstring();if(label.empty())label=p.wstring();t.item.pszText=(LPWSTR)label.c_str();t.item.lParam=(LPARAM)stored;t.item.cChildren=dir?1:0;auto h=TreeView_InsertItem(gTree,&t);if(dir)AddDummy(h);return h;}
void LoadChildren(HTREEITEM h,const std::wstring&path){TreeView_DeleteItem(gTree,TreeView_GetChild(gTree,h));std::vector<fs::directory_entry> v;std::error_code ec;for(fs::directory_iterator it(path,fs::directory_options::skip_permission_denied,ec),end;it!=end&&!ec;it.increment(ec)){auto n=it->path().filename().wstring();if(n==L".git"||n==L"__pycache__")continue;v.push_back(*it);}std::sort(v.begin(),v.end(),[](auto&a,auto&b){if(a.is_directory()!=b.is_directory())return a.is_directory();auto x=a.path().filename().wstring(),y=b.path().filename().wstring();std::transform(x.begin(),x.end(),x.begin(),towlower);std::transform(y.begin(),y.end(),y.begin(),towlower);return x<y;});for(auto&e:v)AddTree(h,e.path(),e.is_directory(ec));}
void SetRoot(const std::wstring&root){gRoot=root;TreeView_DeleteAllItems(gTree);if(root.empty())return;auto h=AddTree(TVI_ROOT,fs::path(root),true);LoadChildren(h,root);TreeView_Expand(gTree,h,TVE_EXPAND);SaveSettings();}
void OpenFile(const std::wstring&p){if(!ConfirmDiscard())return;auto ext=fs::path(p).extension().wstring();std::transform(ext.begin(),ext.end(),ext.begin(),towlower);if(ext!=L".py"&&ext!=L".pyw"){SetStatus(L"当前仅支持 .py 和 .pyw");return;}std::wstring s;if(!DecodeFile(p,s))return;gFile=p;SetEditorText(s);SetStatus(L"已打开文件");if(gRoot.empty())SetRoot(fs::path(p).parent_path().wstring());SetFocus(gEdit);}

void Layout(){RECT r;GetClientRect(gMain,&r);int status=23,tool=44,bottom=r.bottom-status;int rightX=r.right-gRight;int midL=gLeft+5,midR=rightX-5;int out=gOutputCollapsed?32:gSavedOutput;int splitY=bottom-out-5;MoveWindow(gTree,0,tool+34,gLeft,bottom-tool-34,TRUE);MoveWindow(gEdit,midL,tool,midR-midL,splitY-tool,TRUE);MoveWindow(gOutput,midL,splitY+37,midR-midL,bottom-(splitY+37),TRUE);MoveWindow(gStatus,0,bottom,r.right,status,TRUE);MoveWindow(gPy,r.right-420,7,210,30,TRUE);MoveWindow(gRun,r.right-98,7,90,30,TRUE);MoveWindow(gSave,r.right-515,7,80,30,TRUE);MoveWindow(gFolder,68,49,108,24,TRUE);MoveWindow(gClear,midR-150,splitY+8,70,24,TRUE);MoveWindow(gToggle,midR-74,splitY+8,70,24,TRUE);}
void PaintMain(HDC dc){RECT r;GetClientRect(gMain,&r);HBRUSH white=CreateSolidBrush(RGB(255,255,255)),bar=CreateSolidBrush(RGB(251,251,252)),side=CreateSolidBrush(RGB(248,248,249)),border=CreateSolidBrush(RGB(231,232,235));RECT x{0,0,r.right,44};FillRect(dc,&x,bar);x={0,44,gLeft,r.bottom-23};FillRect(dc,&x,side);x={r.right-gRight,44,r.right,r.bottom-23};FillRect(dc,&x,side);x={gLeft,44,gLeft+5,r.bottom-23};FillRect(dc,&x,border);x={r.right-gRight-5,44,r.right-gRight,r.bottom-23};FillRect(dc,&x,border);int out=gOutputCollapsed?32:gSavedOutput;int y=r.bottom-23-out-5;x={gLeft+5,y,r.right-gRight-5,y+5};FillRect(dc,&x,border);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(41,43,49));SelectObject(dc,gUiFont);TextOutW(dc,14,56,L"文件",2);TextOutW(dc,r.right-gRight+14,56,L"侧边栏",3);SetTextColor(dc,RGB(127,131,139));TextOutW(dc,r.right-gRight+14,90,L"内容待定",4);TextOutW(dc,gLeft+16,gOutputCollapsed?r.bottom-50:y+12,L"输出",2);DeleteObject(white);DeleteObject(bar);DeleteObject(side);DeleteObject(border);}

std::wstring Capture(const std::wstring&exe,const std::vector<std::wstring>&args,DWORD timeout,DWORD*code=nullptr){SECURITY_ATTRIBUTES sa{sizeof(sa),nullptr,TRUE};HANDLE rd,wr;if(!CreatePipe(&rd,&wr,&sa,0))return{};SetHandleInformation(rd,HANDLE_FLAG_INHERIT,0);STARTUPINFOW si{sizeof(si)};si.dwFlags=STARTF_USESTDHANDLES;si.hStdOutput=si.hStdError=wr;si.hStdInput=GetStdHandle(STD_INPUT_HANDLE);PROCESS_INFORMATION pi{};std::wstring cmd=QuoteWindowsArg(exe);for(auto&a:args)cmd+=L" "+QuoteWindowsArg(a);BOOL ok=CreateProcessW(exe.c_str(),cmd.data(),nullptr,nullptr,TRUE,CREATE_NO_WINDOW,nullptr,nullptr,&si,&pi);CloseHandle(wr);if(!ok){CloseHandle(rd);return{};}DWORD start=GetTickCount(),avail=0;std::string out;char buf[4096];while(true){while(PeekNamedPipe(rd,nullptr,0,nullptr,&avail,nullptr)&&avail){DWORD got;ReadFile(rd,buf,std::min<DWORD>(avail,sizeof(buf)),&got,nullptr);out.append(buf,got);}if(WaitForSingleObject(pi.hProcess,20)==WAIT_OBJECT_0)break;if(GetTickCount()-start>timeout){TerminateProcess(pi.hProcess,1);break;}}DWORD got;while(ReadFile(rd,buf,sizeof(buf),&got,nullptr)&&got)out.append(buf,got);DWORD ec;GetExitCodeProcess(pi.hProcess,&ec);if(code)*code=ec;CloseHandle(rd);CloseHandle(pi.hThread);CloseHandle(pi.hProcess);return W(out);}
void ValidatePython(std::wstring p){if(p.empty()){wchar_t q[MAX_PATH];if(SearchPathW(nullptr,L"python.exe",nullptr,MAX_PATH,q,nullptr))p=q;else if(SearchPathW(nullptr,L"python3.exe",nullptr,MAX_PATH,q,nullptr))p=q;}auto o=Capture(p,{L"-c",L"import sys; print(sys.version.split()[0])"},5000);auto v=W(ParsePythonVersion(U8(o)));auto*msg=new std::pair<std::wstring,std::wstring>(p,v);PostMessage(gMain,WM_INTERPRETER,0,(LPARAM)msg);}
void DetectPython(){std::thread(ValidatePython,gInterpreter).detach();}
void ChoosePython(){wchar_t p[32768]{};OPENFILENAMEW o{sizeof(o)};o.hwndOwner=gMain;o.lpstrFile=p;o.nMaxFile=32768;o.lpstrFilter=L"Python (python.exe)\0python.exe\0可执行文件\0*.exe\0";o.Flags=OFN_FILEMUSTEXIST|OFN_EXPLORER;if(GetOpenFileNameW(&o))std::thread(ValidatePython,std::wstring(p)).detach();}

void AppendOutput(const std::wstring&s){int n=GetWindowTextLengthW(gOutput);if(n>4*1024*1024){SendMessage(gOutput,EM_SETSEL,0,n-3*1024*1024);SendMessage(gOutput,EM_REPLACESEL,FALSE,(LPARAM)L"");}SendMessage(gOutput,EM_SETSEL,-1,-1);SendMessage(gOutput,EM_REPLACESEL,FALSE,(LPARAM)s.c_str());SendMessage(gOutput,EM_SCROLLCARET,0,0);}
void RunWorker(std::wstring exe,std::wstring file){SECURITY_ATTRIBUTES sa{sizeof(sa),nullptr,TRUE};HANDLE rd,wr;CreatePipe(&rd,&wr,&sa,0);SetHandleInformation(rd,HANDLE_FLAG_INHERIT,0);STARTUPINFOW si{sizeof(si)};si.dwFlags=STARTF_USESTDHANDLES;si.hStdOutput=si.hStdError=wr;PROCESS_INFORMATION pi{};std::wstring cmd=QuoteWindowsArg(exe)+L" -u "+QuoteWindowsArg(file);auto cwd=fs::path(file).parent_path().wstring();SetEnvironmentVariableW(L"PYTHONIOENCODING",L"utf-8");BOOL ok=CreateProcessW(exe.c_str(),cmd.data(),nullptr,nullptr,TRUE,CREATE_NO_WINDOW|CREATE_NEW_PROCESS_GROUP,nullptr,cwd.c_str(),&si,&pi);CloseHandle(wr);if(!ok){CloseHandle(rd);PostMessage(gMain,WM_RUNEND,1,GetLastError());return;}gProcess=pi.hProcess;gJob=CreateJobObjectW(nullptr,nullptr);JOBOBJECT_EXTENDED_LIMIT_INFORMATION ji{};ji.BasicLimitInformation.LimitFlags=JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE;SetInformationJobObject(gJob,JobObjectExtendedLimitInformation,&ji,sizeof(ji));AssignProcessToJobObject(gJob,pi.hProcess);CloseHandle(pi.hThread);char b[4096];DWORD n;while(ReadFile(rd,b,sizeof(b),&n,nullptr)&&n)PostMessage(gMain,WM_APPEND,0,(LPARAM)new std::wstring(W(std::string(b,n))));CloseHandle(rd);DWORD ec;WaitForSingleObject(pi.hProcess,INFINITE);GetExitCodeProcess(pi.hProcess,&ec);CloseHandle(pi.hProcess);gProcess=nullptr;if(gJob){CloseHandle(gJob);gJob=nullptr;}PostMessage(gMain,WM_RUNEND,0,ec);}
void StartRun(){if(gRunning)return;if(gFile.empty()||gDirty){SendMessage(gMain,WM_COMMAND,CMD_SAVE,0);if(gFile.empty()||gDirty)return;}if(gInterpreter.empty()){SetStatus(L"请先选择 Python 解释器");ChoosePython();return;}SetWindowTextW(gOutput,L"");gOutputCollapsed=false;gRunning=true;SetWindowTextW(gRun,L"■ 停止");SetStatus(L"正在运行");Layout();InvalidateRect(gMain,nullptr,TRUE);std::thread(RunWorker,gInterpreter,gFile).detach();}
void StopRun(){if(gJob)TerminateJobObject(gJob,1);else if(gProcess)TerminateProcess(gProcess,1);SetStatus(L"正在停止");}

void ShowCompletion(const std::vector<std::wstring>&v){SendMessage(gPopup,LB_RESETCONTENT,0,0);for(size_t i=0;i<v.size()&&i<100;i++)SendMessage(gPopup,LB_ADDSTRING,0,(LPARAM)v[i].c_str());if(v.empty()){ShowWindow(gPopup,SW_HIDE);return;}POINT p;SendMessage(gEdit,EM_POSFROMCHAR,(WPARAM)&p,SendMessage(gEdit,EM_LINEINDEX,-1,0)+LOWORD(SendMessage(gEdit,EM_GETSEL,0,0)));ClientToScreen(gEdit,&p);ScreenToClient(gMain,&p);MoveWindow(gPopup,p.x,p.y+22,250,std::min<int>(220,24*(int)v.size()+4),TRUE);SendMessage(gPopup,LB_SETCURSEL,0,0);ShowWindow(gPopup,SW_SHOW);SetFocus(gEdit);}
void CompleteStatic(){auto text=EditorText();DWORD a,b;SendMessage(gEdit,EM_GETSEL,(WPARAM)&a,(LPARAM)&b);std::wstring pre;for(int i=(int)a-1;i>=0;i--){wchar_t c=text[i];if(!iswalnum(c)&&c!=L'_')break;pre.insert(pre.begin(),c);}auto c=StaticCompletions(U8(text),U8(pre));std::vector<std::wstring> w;for(auto&s:c)w.push_back(W(s));ShowCompletion(w);}
void DynamicComplete(){auto text=EditorText();DWORD a,b;SendMessage(gEdit,EM_GETSEL,(WPARAM)&a,(LPARAM)&b);auto ctx=AttributeContext(U8(text.substr(0,a)));if(ctx.empty())return;auto module=ResolveModule(ParseImports(U8(text)),ctx);if(module.empty())return;auto key=gInterpreter+L"|"+W(module);{std::lock_guard lk(gCacheMutex);auto i=gModuleCache.find(key);if(i!=gModuleCache.end()){ShowCompletion(i->second);return;}}unsigned req=++gCompletionRequest;SetStatus(L"正在加载模块补全");std::thread([key,module,req]{std::wstring code=L"import importlib,json; m=importlib.import_module('"+W(module)+L"'); print('__PYLITE_JSON__'+json.dumps([x for x in dir(m) if isinstance(x,str)]))";auto o=Capture(gInterpreter,{L"-c",code},7000);std::vector<std::wstring> v;auto pos=o.find(L"__PYLITE_JSON__[");if(pos!=std::wstring::npos){auto s=o.substr(pos+16);std::wregex r(L"\"([A-Za-z_]\\w*)\"");for(auto i=std::wsregex_iterator(s.begin(),s.end(),r);i!=std::wsregex_iterator();++i)v.push_back((*i)[1]);std::sort(v.begin(),v.end(),[](auto&a,auto&b){return PublicFirst(U8(a),U8(b));});if(v.size()>500)v.resize(500);}{std::lock_guard lk(gCacheMutex);gModuleCache[key]=v;}PostMessage(gMain,WM_COMPLETIONS,req,(LPARAM)new std::vector<std::wstring>(v));}).detach();}
void AcceptCompletion(){int i=(int)SendMessage(gPopup,LB_GETCURSEL,0,0);if(i<0)return;wchar_t b[256];SendMessage(gPopup,LB_GETTEXT,i,(LPARAM)b);DWORD a,z;SendMessage(gEdit,EM_GETSEL,(WPARAM)&a,(LPARAM)&z);auto t=EditorText();DWORD start=a;while(start&& (iswalnum(t[start-1])||t[start-1]==L'_'))start--;SendMessage(gEdit,EM_SETSEL,start,a);SendMessage(gEdit,EM_REPLACESEL,TRUE,(LPARAM)b);ShowWindow(gPopup,SW_HIDE);}

void ColorRange(LONG a,LONG b,COLORREF c,bool bold=false){CHARFORMAT2W f{sizeof(f)};f.dwMask=CFM_COLOR|CFM_BOLD;f.crTextColor=c;f.dwEffects=bold?CFE_BOLD:0;SendMessage(gEdit,EM_SETSEL,a,b);SendMessage(gEdit,EM_SETCHARFORMAT,SCF_SELECTION,(LPARAM)&f);}
void Highlight(){if(gFormatting)return;auto s=EditorText();if(s.size()>500000)return;gFormatting=true;DWORD a,b;SendMessage(gEdit,EM_GETSEL,(WPARAM)&a,(LPARAM)&b);BOOL mod=SendMessage(gEdit,EM_GETMODIFY,0,0);SendMessage(gEdit,WM_SETREDRAW,FALSE,0);ColorRange(0,(LONG)s.size(),RGB(41,43,49));std::wregex token(LR"(#[^\r\n]*|(?:'''|\"\"\")[\s\S]*?(?:'''|\"\"\")|'(?:\\.|[^'\\])*'|\"(?:\\.|[^\"\\])*\"|\b\d+(?:\.\d+)?\b|@[A-Za-z_]\w*|\b(?:def|class)\s+([A-Za-z_]\w*)|\b(?:False|None|True|and|as|assert|async|await|break|case|class|continue|def|del|elif|else|except|finally|for|from|global|if|import|in|is|lambda|match|nonlocal|not|or|pass|raise|return|try|while|with|yield)\b)");for(auto i=std::wsregex_iterator(s.begin(),s.end(),token);i!=std::wsregex_iterator();++i){auto x=i->str();COLORREF c=RGB(88,91,112);bool bold=false;if(x[0]==L'#')c=RGB(127,131,139);else if(x[0]==L'\''||x[0]==L'\"')c=RGB(33,151,99);else if(x[0]==L'@')c=RGB(130,80,180);else if(iswdigit(x[0]))c=RGB(31,111,235);else if((*i)[1].matched){c=RGB(130,80,180);bold=true;}else c=RGB(180,60,80);ColorRange((LONG)i->position(),(LONG)(i->position()+i->length()),c,bold);}SendMessage(gEdit,EM_SETSEL,a,b);SendMessage(gEdit,EM_SETMODIFY,mod,0);SendMessage(gEdit,WM_SETREDRAW,TRUE,0);InvalidateRect(gEdit,nullptr,FALSE);gFormatting=false;}

LRESULT CALLBACK EditProc(HWND h,UINT m,WPARAM w,LPARAM l,UINT_PTR,DWORD_PTR){if(m==WM_KEYDOWN){if(IsWindowVisible(gPopup)){if(w==VK_TAB||w==VK_RETURN){AcceptCompletion();return 0;}if(w==VK_ESCAPE){ShowWindow(gPopup,SW_HIDE);return 0;}if(w==VK_DOWN||w==VK_UP){int i=(int)SendMessage(gPopup,LB_GETCURSEL,0,0),n=(int)SendMessage(gPopup,LB_GETCOUNT,0,0);i=w==VK_DOWN?std::min(n-1,i+1):std::max(0,i-1);SendMessage(gPopup,LB_SETCURSEL,i,0);return 0;}}if(w==VK_TAB){SendMessage(h,EM_REPLACESEL,TRUE,(LPARAM)(GetKeyState(VK_SHIFT)&0x8000?L"":L"    "));return 0;}}auto r=DefSubclassProc(h,m,w,l);if(m==WM_CHAR&&(iswalnum((wchar_t)w)||w==L'_'))CompleteStatic();if(m==WM_CHAR&&w==L'.')DynamicComplete();return r;}

void RegisterOpen(bool remove){wchar_t exe[MAX_PATH];GetModuleFileNameW(nullptr,exe,MAX_PATH);if(remove){SHDeleteKeyW(HKEY_CURRENT_USER,L"Software\\Classes\\Applications\\PyLite.exe");SHDeleteKeyW(HKEY_CURRENT_USER,L"Software\\Classes\\PyLite.File");}else{HKEY k;RegCreateKeyExW(HKEY_CURRENT_USER,L"Software\\Classes\\Applications\\PyLite.exe\\shell\\open\\command",0,nullptr,0,KEY_WRITE,nullptr,&k,nullptr);auto cmd=QuoteWindowsArg(exe)+L" \"%1\"";RegSetValueExW(k,nullptr,0,REG_SZ,(BYTE*)cmd.c_str(),(DWORD)((cmd.size()+1)*2));RegCloseKey(k);RegCreateKeyExW(HKEY_CURRENT_USER,L"Software\\Classes\\Applications\\PyLite.exe\\SupportedTypes",0,nullptr,0,KEY_WRITE,nullptr,&k,nullptr);RegSetValueExW(k,L".py",0,REG_NONE,nullptr,0);RegSetValueExW(k,L".pyw",0,REG_NONE,nullptr,0);RegCloseKey(k);RegCreateKeyExW(HKEY_CURRENT_USER,L"Software\\Classes\\PyLite.File\\shell\\open\\command",0,nullptr,0,KEY_WRITE,nullptr,&k,nullptr);RegSetValueExW(k,nullptr,0,REG_SZ,(BYTE*)cmd.c_str(),(DWORD)((cmd.size()+1)*2));RegCloseKey(k);for(auto e:{L".py",L".pyw"}){std::wstring p=L"Software\\Classes\\"+std::wstring(e)+L"\\OpenWithProgids";RegCreateKeyExW(HKEY_CURRENT_USER,p.c_str(),0,nullptr,0,KEY_WRITE,nullptr,&k,nullptr);RegSetValueExW(k,L"PyLite.File",0,REG_NONE,nullptr,0);RegCloseKey(k);}}SHChangeNotify(SHCNE_ASSOCCHANGED,SHCNF_IDLIST,nullptr,nullptr);SetStatus(remove?L"已从“打开方式”移除":L"已注册到“打开方式”");}

HMENU Menus(){HMENU bar=CreateMenu(),f=CreatePopupMenu(),e=CreatePopupMenu(),r=CreatePopupMenu(),t=CreatePopupMenu();AppendMenuW(f,MF_STRING,CMD_NEW,L"新建\tCtrl+N");AppendMenuW(f,MF_STRING,CMD_OPEN,L"打开文件…\tCtrl+O");AppendMenuW(f,MF_STRING,CMD_FOLDER,L"打开文件夹…\tCtrl+Shift+O");AppendMenuW(f,MF_SEPARATOR,0,nullptr);AppendMenuW(f,MF_STRING,CMD_SAVE,L"保存\tCtrl+S");AppendMenuW(f,MF_STRING,CMD_SAVEAS,L"另存为…\tCtrl+Shift+S");AppendMenuW(f,MF_SEPARATOR,0,nullptr);AppendMenuW(f,MF_STRING,CMD_EXIT,L"退出");AppendMenuW(e,MF_STRING,CMD_UNDO,L"撤销\tCtrl+Z");AppendMenuW(e,MF_STRING,CMD_REDO,L"重做\tCtrl+Y");AppendMenuW(e,MF_SEPARATOR,0,nullptr);AppendMenuW(e,MF_STRING,CMD_CUT,L"剪切");AppendMenuW(e,MF_STRING,CMD_COPY,L"复制");AppendMenuW(e,MF_STRING,CMD_PASTE,L"粘贴");AppendMenuW(e,MF_STRING,CMD_ALL,L"全选\tCtrl+A");AppendMenuW(r,MF_STRING,CMD_RUN,L"运行\tF5");AppendMenuW(r,MF_STRING,CMD_STOP,L"停止\tShift+F5");AppendMenuW(r,MF_STRING,CMD_TOGGLE,L"折叠/展开输出\tCtrl+J");AppendMenuW(t,MF_STRING,CMD_SELECTPY,L"选择 Python…");AppendMenuW(t,MF_SEPARATOR,0,nullptr);AppendMenuW(t,MF_STRING,CMD_REGISTER,L"注册到“打开方式”");AppendMenuW(t,MF_STRING,CMD_UNREGISTER,L"从“打开方式”移除");AppendMenuW(t,MF_STRING,CMD_ABOUT,L"关于");AppendMenuW(bar,MF_POPUP,(UINT_PTR)f,L"文件");AppendMenuW(bar,MF_POPUP,(UINT_PTR)e,L"编辑");AppendMenuW(bar,MF_POPUP,(UINT_PTR)r,L"运行");AppendMenuW(bar,MF_POPUP,(UINT_PTR)t,L"工具");return bar;}

LRESULT CALLBACK Proc(HWND h,UINT m,WPARAM w,LPARAM l){switch(m){case WM_CREATE:{gMain=h;LoadLibraryW(L"Msftedit.dll");gUiFont=CreateFontW(-14,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Segoe UI");gCodeFont=CreateFontW(-17,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,FIXED_PITCH,L"Cascadia Code");gTree=CreateWindowExW(0,WC_TREEVIEWW,L"",WS_CHILD|WS_VISIBLE|TVS_HASBUTTONS|TVS_HASLINES|TVS_LINESATROOT|TVS_SHOWSELALWAYS,0,0,0,0,h,(HMENU)ID_TREE,gInst,nullptr);gEdit=CreateWindowExW(WS_EX_CLIENTEDGE,MSFTEDIT_CLASS,L"",WS_CHILD|WS_VISIBLE|WS_VSCROLL|WS_HSCROLL|ES_MULTILINE|ES_WANTRETURN|ES_NOHIDESEL,0,0,0,0,h,(HMENU)ID_EDIT,gInst,nullptr);gOutput=CreateWindowExW(WS_EX_CLIENTEDGE,MSFTEDIT_CLASS,L"",WS_CHILD|WS_VISIBLE|WS_VSCROLL|ES_MULTILINE|ES_READONLY,0,0,0,0,h,(HMENU)ID_OUTPUT,gInst,nullptr);gStatus=CreateWindowExW(0,STATUSCLASSNAMEW,L"就绪",WS_CHILD|WS_VISIBLE,0,0,0,0,h,(HMENU)ID_STATUS,gInst,nullptr);gPy=CreateWindowExW(0,L"BUTTON",L"选择 Python",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,0,0,0,0,h,(HMENU)ID_PY,gInst,nullptr);gRun=CreateWindowExW(0,L"BUTTON",L"▶ 运行",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,0,0,0,0,h,(HMENU)ID_RUN,gInst,nullptr);gSave=CreateWindowExW(0,L"BUTTON",L"保存",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,0,0,0,0,h,(HMENU)ID_SAVE,gInst,nullptr);gFolder=CreateWindowExW(0,L"BUTTON",L"打开文件夹",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,0,0,0,0,h,(HMENU)CMD_FOLDER,gInst,nullptr);gClear=CreateWindowExW(0,L"BUTTON",L"清空",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,0,0,0,0,h,(HMENU)ID_CLEAR,gInst,nullptr);gToggle=CreateWindowExW(0,L"BUTTON",L"折叠",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,0,0,0,0,h,(HMENU)ID_TOGGLE,gInst,nullptr);gPopup=CreateWindowExW(WS_EX_TOPMOST|WS_EX_TOOLWINDOW,L"LISTBOX",L"",WS_CHILD|WS_BORDER|LBS_NOTIFY|WS_VSCROLL,0,0,0,0,h,(HMENU)ID_POPUP,gInst,nullptr);for(HWND x:{gTree,gStatus,gPy,gRun,gSave,gFolder,gClear,gToggle,gPopup})SendMessage(x,WM_SETFONT,(WPARAM)gUiFont,TRUE);SendMessage(gEdit,WM_SETFONT,(WPARAM)gCodeFont,TRUE);SendMessage(gOutput,WM_SETFONT,(WPARAM)gCodeFont,TRUE);SendMessage(gEdit,EM_SETEVENTMASK,0,ENM_CHANGE|ENM_SELCHANGE);SetWindowSubclass(gEdit,EditProc,1,0);SetTimer(h,1,350,nullptr);LoadSettings();if(!gRoot.empty()&&fs::exists(gRoot))SetRoot(gRoot);DetectPython();UpdateTitle();return 0;}
case WM_SIZE:Layout();return 0;case WM_PAINT:{PAINTSTRUCT p;auto dc=BeginPaint(h,&p);PaintMain(dc);EndPaint(h,&p);return 0;}case WM_GETMINMAXINFO:{auto*x=(MINMAXINFO*)l;x->ptMinTrackSize={900,560};return 0;}
case WM_TIMER:if(gDirty)Highlight();return 0;
case WM_LBUTTONDOWN:{RECT r;GetClientRect(h,&r);int x=GET_X_LPARAM(l),y=GET_Y_LPARAM(l),out=gOutputCollapsed?32:gSavedOutput,sy=r.bottom-23-out-5;if(abs(x-gLeft)<6)gDrag=1;else if(abs(x-(r.right-gRight))<6)gDrag=2;else if(abs(y-sy)<6&&x>gLeft&&x<r.right-gRight)gDrag=3;if(gDrag){SetCapture(h);gDragStart={x,y};gDragValue=gDrag==1?gLeft:gDrag==2?gRight:gSavedOutput;}return 0;}
case WM_MOUSEMOVE:if(gDrag){RECT r;GetClientRect(h,&r);int x=GET_X_LPARAM(l),y=GET_Y_LPARAM(l);if(gDrag==1)gLeft=std::clamp<LONG>(gDragValue+x-gDragStart.x,145,r.right-gRight-430);if(gDrag==2)gRight=std::clamp<LONG>(gDragValue-(x-gDragStart.x),150,r.right-gLeft-430);if(gDrag==3){gSavedOutput=std::clamp<LONG>(gDragValue-(y-gDragStart.y),80,r.bottom-160);gOutputCollapsed=false;}Layout();InvalidateRect(h,nullptr,TRUE);}return 0;case WM_LBUTTONUP:if(gDrag){gDrag=0;ReleaseCapture();SaveSettings();}return 0;
case WM_NOTIFY:{auto*n=(NMHDR*)l;if(n->idFrom==ID_TREE&&n->code==TVN_ITEMEXPANDINGW){auto*t=(NMTREEVIEWW*)l;if(t->action==TVE_EXPAND){TVITEMW i{};i.mask=TVIF_PARAM;i.hItem=t->itemNew.hItem;TreeView_GetItem(gTree,&i);if(i.lParam)LoadChildren(i.hItem,*(std::wstring*)i.lParam);}}if(n->idFrom==ID_TREE&&n->code==NM_DBLCLK){auto hti=TreeView_GetSelection(gTree);TVITEMW i{};i.mask=TVIF_PARAM;i.hItem=hti;TreeView_GetItem(gTree,&i);if(i.lParam&&!fs::is_directory(*(std::wstring*)i.lParam))OpenFile(*(std::wstring*)i.lParam);}if(n->idFrom==ID_EDIT&&(n->code==EN_CHANGE||n->code==EN_SELCHANGE)){if(!gFormatting){gDirty=SendMessage(gEdit,EM_GETMODIFY,0,0);UpdateTitle();}CHARRANGE c;SendMessage(gEdit,EM_EXGETSEL,0,(LPARAM)&c);int line=(int)SendMessage(gEdit,EM_LINEFROMCHAR,c.cpMin,0),base=(int)SendMessage(gEdit,EM_LINEINDEX,line,0);std::wstring s=L"Ln "+std::to_wstring(line+1)+L", Col "+std::to_wstring(c.cpMin-base+1)+L"    "+gEncoding+L"    Python";SendMessage(gStatus,SB_SETTEXT,1,(LPARAM)s.c_str());}return 0;}
case WM_COMMAND:{int id=LOWORD(w);if(id==ID_EDIT&&HIWORD(w)==EN_CHANGE&&!gFormatting){gDirty=SendMessage(gEdit,EM_GETMODIFY,0,0);UpdateTitle();return 0;}if(id==ID_PY||id==CMD_SELECTPY)ChoosePython();else if(id==ID_RUN||id==CMD_RUN)(gRunning?StopRun():StartRun());else if(id==CMD_STOP)StopRun();else if(id==CMD_NEW){if(ConfirmDiscard()){gFile.clear();gEncoding=L"UTF-8";SetEditorText(L"");}}else if(id==CMD_OPEN){auto p=FileDialog(false);if(!p.empty())OpenFile(p);}else if(id==CMD_FOLDER){auto p=FolderDialog();if(!p.empty())SetRoot(p);}else if(id==CMD_SAVE||id==ID_SAVE){if(gFile.empty()){auto p=FileDialog(true);if(!p.empty())SaveTo(p);}else SaveTo(gFile);}else if(id==CMD_SAVEAS){auto p=FileDialog(true);if(!p.empty()){gEncoding=L"UTF-8";SaveTo(p);}}else if(id==CMD_EXIT)SendMessage(h,WM_CLOSE,0,0);else if(id==CMD_UNDO)SendMessage(gEdit,EM_UNDO,0,0);else if(id==CMD_REDO)SendMessage(gEdit,EM_REDO,0,0);else if(id==CMD_CUT)SendMessage(gEdit,WM_CUT,0,0);else if(id==CMD_COPY)SendMessage(gEdit,WM_COPY,0,0);else if(id==CMD_PASTE)SendMessage(gEdit,WM_PASTE,0,0);else if(id==CMD_ALL)SendMessage(gEdit,EM_SETSEL,0,-1);else if(id==CMD_TOGGLE||id==ID_TOGGLE){gOutputCollapsed=!gOutputCollapsed;Layout();InvalidateRect(h,nullptr,TRUE);SaveSettings();}else if(id==ID_CLEAR){SetWindowTextW(gOutput,L"");}else if(id==CMD_REGISTER)RegisterOpen(false);else if(id==CMD_UNREGISTER)RegisterOpen(true);else if(id==CMD_ABOUT)MessageBoxW(h,L"PyLite 1.0\n轻量级 Python 编辑器\n原生 Win32 便携版",L"关于",MB_OK);else if(id==ID_POPUP&&HIWORD(w)==LBN_DBLCLK)AcceptCompletion();return 0;}
case WM_APPEND:{auto*s=(std::wstring*)l;AppendOutput(*s);delete s;return 0;}case WM_RUNEND:{gRunning=false;SetWindowTextW(gRun,L"▶ 运行");auto ec=(DWORD)l;AppendOutput(L"\r\n[进程结束，退出码 "+std::to_wstring(ec)+L"]\r\n");SetStatus(ec==0?L"运行成功":L"运行失败");return 0;}case WM_INTERPRETER:{auto*p=(std::pair<std::wstring,std::wstring>*)l;if(!p->second.empty()){gInterpreter=p->first;SetWindowTextW(gPy,(L"● "+p->second).c_str());SetStatus(L"Python 解释器有效");{std::lock_guard lk(gCacheMutex);gModuleCache.clear();}SaveSettings();}else{SetWindowTextW(gPy,L"选择 Python");SetStatus(L"Python 解释器不可用");}delete p;return 0;}case WM_COMPLETIONS:{auto*v=(std::vector<std::wstring>*)l;if((unsigned)w==gCompletionRequest){ShowCompletion(*v);SetStatus(v->empty()?L"模块补全不可用":L"模块补全已加载");}delete v;return 0;}
case WM_CLOSE:if(!ConfirmDiscard())return 0;SaveSettings();if(gJob)TerminateJobObject(gJob,1);DestroyWindow(h);return 0;case WM_DESTROY:DeleteObject(gUiFont);DeleteObject(gCodeFont);PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}

int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int show){gInst=hi;CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);INITCOMMONCONTROLSEX ic{sizeof(ic),ICC_TREEVIEW_CLASSES|ICC_BAR_CLASSES|ICC_STANDARD_CLASSES};InitCommonControlsEx(&ic);int argc;auto argv=CommandLineToArgvW(GetCommandLineW(),&argc);if(argc>1&&wcscmp(argv[1],L"--register-open-with")==0){gMain=nullptr;RegisterOpen(false);return 0;}if(argc>1&&wcscmp(argv[1],L"--unregister-open-with")==0){gMain=nullptr;RegisterOpen(true);return 0;}WNDCLASSEXW wc{sizeof(wc),CS_HREDRAW|CS_VREDRAW,Proc,0,0,hi,LoadIconW(hi,MAKEINTRESOURCEW(1)),LoadCursor(nullptr,IDC_ARROW),(HBRUSH)(COLOR_WINDOW+1),nullptr,L"PyLiteWindow",LoadIconW(hi,MAKEINTRESOURCEW(1))};RegisterClassExW(&wc);auto h=CreateWindowExW(0,wc.lpszClassName,L"未命名.py — PyLite",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1100,760,nullptr,Menus(),hi,nullptr);int parts[2]={500,-1};SendMessage(gStatus,SB_SETPARTS,2,(LPARAM)parts);ShowWindow(h,show);UpdateWindow(h);if(argc>1&&argv[1][0]!=L'-')OpenFile(argv[1]);LocalFree(argv);ACCEL a[]={{FVIRTKEY|FCONTROL,'N',CMD_NEW},{FVIRTKEY|FCONTROL,'O',CMD_OPEN},{FVIRTKEY|FCONTROL|FSHIFT,'O',CMD_FOLDER},{FVIRTKEY|FCONTROL,'S',CMD_SAVE},{FVIRTKEY|FCONTROL|FSHIFT,'S',CMD_SAVEAS},{FVIRTKEY|FCONTROL,'Z',CMD_UNDO},{FVIRTKEY|FCONTROL,'Y',CMD_REDO},{FVIRTKEY|FCONTROL,'A',CMD_ALL},{FVIRTKEY,VK_F5,CMD_RUN},{FVIRTKEY|FSHIFT,VK_F5,CMD_STOP},{FVIRTKEY|FCONTROL,'J',CMD_TOGGLE}};auto ac=CreateAcceleratorTableW(a,ARRAYSIZE(a));MSG m;while(GetMessageW(&m,nullptr,0,0)){if(!TranslateAcceleratorW(h,ac,&m)){TranslateMessage(&m);DispatchMessageW(&m);}}DestroyAcceleratorTable(ac);CoUninitialize();return(int)m.wParam;}
